### PR TITLE
Use the filename as ArtifactId : Add Generated Function for Options

### PR DESCRIPTION
**Pull request by jmorille**
As discut at issue https://github.com/finn-no/gulp-maven-deploy/issues/5
use an function to generate the maven deploy configuration.

The use case look that
```javascript
gulp.task('deploy', function () {
  var maven = require('gulp-maven-deploy');
  gulp.src('dist/**/*.apk') 
    .pipe(maven.deploy(function (fileParsed, cb) {
        return {
          'config': {
            'groupId':  'com.mygroup',
            'artifactId': fileParsed.name,
            'type': fileParsed.extname,
            'repositories': [  {  'id': 'some-repo-id',  'url': 'http://some-repo/url' }  ]
          }
        };
      }
    ))
}); 
```

### CODE REVIEW

**Comment by leftieFriele** [comment]
Ok, I finally got Maven onto my machine so I got to see this running. Sorry about the back and forth and my inability to understand what you meant to do. It seems fine to add this.

There are three things which must be done:
- You're using path.parse which came in Node 0.12, this seems unnecessary and this plugin should run on 0.11 and 0.10 versions of Node.
- It would also be great if you could update the samples with the callback-config option too.
- Could you also maintain the indention that was in the original project (I'll add some config to make sure it'll be fixed automatically... sorry about that.

**Comment by jmorille** [comment]
I am pushing another pull request, with the chages that you asking.
 - I have completed the Doc and Sample 
 - and re code the nodejs path.parse in order to keep compatibility.
 - For the formatting rule, I am sorry but they are no file to describe your format rules.
Personaly I am using .editorconfig descriptor (http://editorconfig.org/)

I do more test and they are a problem with the maven-deploy plugin in multiple file.
For all the file they use the   *archive path dist/back2.apk* in -Dfile options
```shell
Executing command: mvn -B deploy:deploy-file -Dpackaging=apk -Dfile=dist/back2.apk -DgroupId=mygroup -DartifactId=android-armv7-debug-unaligned -Dversion=0.0.1 -DrepositoryId=...

archive path dist/back2.apk
Executing command: mvn -B deploy:deploy-file -Dpackaging=apk -Dfile=dist/back2.apk -DgroupId=mygroup -DartifactId=android-armv7-debug-unaligned -Dversion=0.0.1 -DrepositoryId=...
````

**Comment by leftieFriele** [comment]
I'll merge it once the tests pass @jmorille

**Comment by micha149** [comment]
@jmorille did you noticed issue #8? Would this satisfy your needs, too?

**Pull request closed without merging**
