### PR TITLE
fix(vinyl version conflict): Add a cast to vinyl's File so as to force version

### PR DESCRIPTION
**Pull request by sebsebseb1982**
Tests weren't OK before commit. They are still not working after :)

### CODE REVIEW

**Comment by micha149** [comment]
Hmm. Tests on travis are passing…

**Comment by micha149** [comment]
@sebsebseb1982 will this also fix issue #19?

**Comment by sebsebseb1982** [comment]
I think it should

**Comment by smolnikov** [comment]
@micha149 could you promote new version to npm?

**Comment by micha149** [comment]
I've released [v1.0.2](https://github.com/micha149/gulp-maven-deploy/releases/tag/v1.0.2) on npm!

**Pull request merged**
